def Dummy_Path():
  global _hidden_verificationVariable=0
  set_target_payload(1.970000, [-0.003000, -0.010000, 0.017000], [0.004766, 0.004766, 0.004766, 0.000000, 0.000000, 0.000000])
  set_tool_communication(False, 115200, 0, 1, 1.5, 3.5)
  set_tool_output_mode(0)
  set_tool_digital_output_mode(0, 2)
  set_tool_digital_output_mode(1, 2)
  set_tool_voltage(0)
  set_standard_analog_input_domain(0, 1)
  set_standard_analog_input_domain(1, 1)
  set_tool_analog_input_domain(0, 1)
  set_tool_analog_input_domain(1, 1)
  set_analog_outputdomain(0, 0)
  set_analog_outputdomain(1, 0)
  set_input_actions_to_default()
  set_gravity([0.0, -9.82, 6.013015783813504E-16])
  motion_version_set(2)
  tool_wrench_limit_disable()
  set_tcp(p[0.0,0.0,0.0,0.0,0.0,0.0])
  set_safety_mode_transition_hardness(1)
  global line_length=1
  global line_incr=0.1
  global avoid_start=5
  global avoid_end=7
  global avoid_gap=0.05
  global Plane_1=p[0.0,0.58,0.0,-1.5707963267948963,-2.9874637964168546E-16,-2.9874637964168546E-16]
  # begin: URCap Installation Node
  #   Source: UR Connect, 2.3.8, Universal Robots
  #   Type: UR Connect
  myurRPC = rpc_factory("xmlrpc","http://127.0.0.1:40474")
  # end: URCap Installation Node
  step_count_558bdad5_74d3_42b2_9a22_95c36733b8f2 = 0.0
  thread Step_Counter_Thread_07701ccd_ac6c_4baa_90b4_336dc1b9c782():
    while (True):
      step_count_558bdad5_74d3_42b2_9a22_95c36733b8f2 = step_count_558bdad5_74d3_42b2_9a22_95c36733b8f2 + 1.0
      sync()
    end
  end
  run Step_Counter_Thread_07701ccd_ac6c_4baa_90b4_336dc1b9c782()
  global Tmp1_p=p[.308197528239, .200952848898, 1.212577409890, -1.500617001311, .096591502570, -1.942084517693]
  global Tmp1_q=[2.9922775051327015, -1.8204617628859179, 0.7854625361952244, 0.6468829346793701, 1.081932385811806, 2.2461432469487175]
  global Tmp2_p=p[-.215537331320, .339862281058, 1.244844388379, -1.453965512348, -.560096017943, -.789013712763]
  global Tmp2_q=[3.0693981647491455, -2.002010484735006, 0.261266056691305, 0.8101395803638916, 0.07373906672000885, 3.208488702774048]
  global p_start_h_p=p[-.999997408249, .400000000000, .500006434304, .000041430541, 2.221422899869, 2.221426094581]
  global p_start_h_q=[3.070528733662697, -2.5403255247363887, -1.0453963810477394, 0.3283725906749231, 0.0738736397653641, 3.2576352572049876]
  def move_Low():
    $ 47 "move_Low" "noBreak"
    $ 48 "position_High≔get_actual_tcp_pose()"
    global position_High= get_actual_tcp_pose ()
    $ 49 "position_Low≔pose_trans(position_High, p[0, 0, avoid_gap, 0, 0, 0])"
    global position_Low= pose_trans (position_High, p[0, 0, avoid_gap, 0, 0, 0])
    $ 50 "movel(position_Low, a=0.05, v=2, r=0)"
    movel(position_Low, a=0.05, v=2, r=0)
  end
  def move_High():
    $ 51 "move_High" "noBreak"
    $ 52 "position_Low_1≔get_actual_tcp_pose()"
    global position_Low_1= get_actual_tcp_pose ()
    $ 53 "position_High_1≔pose_trans(position_Low_1, p[0, 0, -avoid_gap, 0, 0, 0])"
    global position_High_1= pose_trans (position_Low_1, p[0, 0, -avoid_gap, 0, 0, 0])
    $ 54 "movel(position_High_1, a=0.05, v=2, r=0)"
    movel(position_High_1, a=0.05, v=2, r=0)
  end
  $ 2 "Robot Program"
  $ 3 "'Set global variables for current program'"
  # 'Set global variables for current program'
  $ 4 "avoid_start≔read_input_float_register(18)"
  global avoid_start=read_input_float_register(18)
  $ 5 "avoid_end≔read_input_float_register(19)"
  global avoid_end=read_input_float_register(19)
  $ 6 "avoid_gap≔read_input_float_register(20)"
  global avoid_gap=read_input_float_register(20)
  $ 7 "line_incr≔read_input_float_register(21)"
  global line_incr=read_input_float_register(21)
  $ 8 "line_length≔read_input_float_register(22)"
  global line_length=read_input_float_register(22)
  $ 9 "Popup: variables done"
  popup("variables done", "Message", False, False, blocking=True)
  $ 10 "Home"
  movej([1.5704206228256226, -1.3090128761580964, 2.443455998097555, -1.134462670688965, 1.5708153247833252, 1.5707963267948966], a=1.3962634015954636, v=1.0471975511965976)
  $ 11 "MoveJ"
  $ 12 "Tmp1" "breakAfter"
  movej(get_inverse_kin(Tmp1_p, qnear=Tmp1_q), a=1.3962634015954636, v=1.0471975511965976)
  $ 13 "Tmp2" "breakAfter"
  movej(get_inverse_kin(Tmp2_p, qnear=Tmp2_q), a=1.3962634015954636, v=1.0471975511965976)
  $ 14 "MoveJ"
  $ 15 "p_start_h" "breakAfter"
  movej(get_inverse_kin(p_start_h_p, qnear=p_start_h_q), a=1.3962634015954636, v=1.0471975511965976)
  $ 16 "speed≔2"
  global speed=2
  $ 17 "acc≔0.05"
  global acc=0.05
  $ 18 "cur_idx≔0"
  global cur_idx=0
  $ 19 "line_nb_steps≔floor(line_length / line_incr)"
  global line_nb_steps=floor(line_length / line_incr)
  $ 20 "'All movement are relative to p_start'"
  # 'All movement are relative to p_start'
  $ 21 "p_start_l≔pose_trans(get_actual_tcp_pose(), p[0, 0, avoid_gap, 0, 0, 0])"
  global p_start_l= pose_trans ( get_actual_tcp_pose (), p[0, 0, avoid_gap, 0, 0, 0])
  $ 22 "Loop cur_idx ≤ line_nb_steps"
  while (cur_idx  <=  line_nb_steps):
    $ 23 "'Handle obstacle'"
    # 'Handle obstacle'
    $ 24 "If (cur_idx ≥ avoid_start - 1)  and  (cur_idx ≤ avoid_end + 1)"
    if ((cur_idx  >=  avoid_start - 1)   and   (cur_idx  <=  avoid_end + 1)):
      $ 25 "If cur_idx ≠ 0"
      if (cur_idx  !=  0):
        $ 26 "Popup: apply force"
        popup("apply force", "Message", False, False, blocking=True)
        $ 27 "Call move_High"
        move_High()
      end
      $ 28 "'Move sideways to clear the obstacle'"
      # 'Move sideways to clear the obstacle'
      $ 29 "avoid_length≔(avoid_end + 1) * line_incr"
      global avoid_length=(avoid_end + 1) * line_incr
      $ 30 "p_cur = pose_trans(p_start_h, p[-avoid_length, 0, 0, 0, 0, 0])"
      p_cur =  pose_trans (p_start_h_p, p[-avoid_length, 0, 0, 0, 0, 0])
      $ 31 "movel(p_cur, a=acc, v=speed, r=0)"
      movel(p_cur, a=acc, v=speed, r=0)
      $ 32 "'Move to low position and update current index'"
      # 'Move to low position and update current index'
      $ 33 "Call move_Low"
      move_Low()
      $ 34 "cur_idx≔avoid_end + 1"
      global cur_idx=avoid_end + 1
    end
    $ 35 "If cur_idx ≟ 0"
    if (cur_idx  ==  0):
      $ 36 "Call move_Low"
      move_Low()
    end
    $ 37 "Popup: apply force"
    popup("apply force", "Message", False, False, blocking=True)
    $ 38 "'Move to next target (if not already at last)'"
    # 'Move to next target (if not already at last)'
    $ 39 "cur_idx≔cur_idx + 1"
    global cur_idx=cur_idx + 1
    $ 40 "If cur_idx ≤ line_nb_steps"
    if (cur_idx  <=  line_nb_steps):
      $ 41 "p_cur = pose_trans(p_start_l, p[-cur_idx * line_incr, 0, 0, 0, 0, 0])"
      p_cur =  pose_trans (p_start_l, p[-cur_idx * line_incr, 0, 0, 0, 0, 0])
      $ 42 "movel(p_cur, a=acc, v=speed, r=0)"
      movel(p_cur, a=acc, v=speed, r=0)
    end
  end
  $ 43 "'Move back to safe height and go to start of line'"
  # 'Move back to safe height and go to start of line'
  $ 44 "Call move_High"
  move_High()
  $ 45 "MoveL"
  $ 46 "p_start_h" "breakAfter"
  movel(p_start_h_p, a=1.2, v=0.25)
end
